language: node_js
node_js:
  - "6.11"
#  - "stable"
services:
  - docker
notifications:
  slack: 
      rooms:
            - redklouds1:075OXfOwTatGBCewiUwzqylS
cache:
  directories:
    - node_modules

before_script:
  - npm install -g mocha chai
  
  - npm test
script:
  - docker build -t test .
  - docker run -d --name test test
  - docker ps | grep -q test
after_success:
  - echo "After successful build"
  - sh .travis/deploy_dockerhub.sh

