language: node_js
node_js:
  - "6.11"
  - "stable"
services:
  - docker
notifications:
  slack: 
      rooms:
            - redklouds1:075OXfOwTatGBCewiUwzqylS
cache:
  directories:
    - node_modules
script:
  - npm test

